print('Giraffe\nAcademy')
print('Giraffe\"Academy')
print('Giraffe\tAcademy')
print('Giraffe\\Academy')

phrase = 'Giraffe Academy'
print(phrase + ' is cool')
print(phrase.lower())
print(phrase.upper())
print(phrase.lower().islower())
print(phrase.upper().isupper())
print(phrase.lower().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[1])
print(phrase.index('a'))
print(phrase.index('G'))
print(phrase.index('Acade'))
print(phrase.replace('Giraffe', 'Elephant'))
